### ISSUE TITLE
Calculating and Representing Vectors/Velocity with GPS Locations

### ISSUE THREAD

**Issue by zkhalapyan** [zkhalapyan/KimonoNet#1]
I am currently representing GeoVectors with _<dLongitude/dt, dLatitude/dt>_ calculated by _<(Longitude_Current - Longitude_Previous)/dt, (Latitude_Current - Latitude_Previous)/dt>_, where dt is calculated by _timestamp_current - timestamp_previous_.

Is this a correct representation for the algorithms? Another possibility is to convert this into meters/second, or various other forms.

Another question is how to calculate the difference between two GPS points that have different accuracies?

**Comment by ebollens** [comment]
The algorithm does not assume any representation of format - you will need to be able to convert from lon/lat into distance, but, so long as you can do that, representation doesn't matter.

**Comment by zkhalapyan** [comment]
After doing more research, it seems that most GPS based flight velocity calculations produce speed in m/s and a [bearing](http://en.wikipedia.org/wiki/Bearing_%28navigation%29) value that acts as the direction vector.

Furthermore, there are two common ways of calculating speed: the [haversine formula](http://www.movable-type.co.uk/scripts/latlong.html) and the [inverse formula](http://www.ngs.noaa.gov/PUBS_LIB/inverse.pdf) (this paper was written in April, 1975, but is a very famous publication that introduced the inverse formula). The haversine formula uses a spherical model of the Earth resulting in up to 0.3% error while the inverse formula, used in Android's [Location class's source code](http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/2.2_r1.1/android/location/Location.java), is very accurate but a bit more complex treating the Earth as an ellipsoid.

The more important question here is if we should switch to _<speed, bearing>_ version for representing GPS-based velocity vectors?

**Comment by ebollens** [comment]
Right now, our velocity packet has the following:

```
SPEED (4)
BEARING (8)
```

Is this indeed accurate? If so, I will resolve this issue.

**Comment by zkhalapyan** [comment]
This is correct. Internally, speed is represented with a single-precision 4 byte float value while bearing is a double-precision 8 byte float (double).

**Comment by zkhalapyan** [comment]
Correction to last comment: both speed and bearing are represented by float values produced by the inverse formula.
