### ISSUE TITLE
Port Configuration Issues in Simulation Mode

### ISSUE THREAD

**Issue by zkhalapyan** [zkhalapyan/KimonoNet#10]
Given that two sockets cannot be bound to the same port number within a simulation environment, there needs to be a way of selecting different port numbers that don't conflict with each other. Several solutions that are available are described bellow: 

**Use Peer's MAC Address or Peer's Name**
It seems that since all peers have a unique MAC address it would be easy to convert this address to unique port numbers. However, this is not very simple as a MAC-48 is only 6 bytes (including padding, 8) and port numbers are represented by 4 byte integers. How would you generate three different unique port numbers given one MAC address?

**Have two Operational Modes**
The best approach although with a bit of complexity is to add a layer of abstraction for selecting port numbers and implement two versions of this abstraction: a simulation mode and a production mode. In case of the simulation mode, the abstraction will issue unique port numbers to a peer and will store it in a <peer, port-number> mapping for the rest of the peers to see. On the production version, with much less complexity, port numbers will be hard coded or set within the environment variables. In production mode, it is assumed that each peer will most likely get an individual NIC to work with and hence, eliminate the conflicting-port number issue.

Given these two scenarios, I would appreciate some feedback or comments before moving forward. Is there anything I haven't thought about or a use case I didn't include?

**Comment by zkhalapyan** [comment]
Neither of these solutions work: we will have to move into a simulation environment or a UDP multicast packets. 

The only simulation environment for Java that I found is [SWANS](http://jist.ece.cornell.edu/), but given that it was last updated in 2005, I really don't want to get into it. Another option is to use [multicast packets](http://docs.oracle.com/javase/1.4.2/docs/api/java/net/MulticastSocket.html), but I am not sure how much inefficiency this will introduce. In either case, it is important to distinguish between simulation mode and production mode abstractions.

**Comment by zkhalapyan** [comment]
The solution for this issue has been finalized and committed. Issue was solved by introducing a **PortConfiguration** class that includes port and network related configuration, and an interface **PortConfigurationProvider** that produces a port configuration given an agent. 

Current implementation of **PortConfiguration** contains beacon service port number, data sending port number, data receiving port number, and also indicates whether the connection should use multicast protocol as opposed to a simple UDP connection. Furthermore, a **SimulationPortConfigurationProvider** produces port configuration to be used in simulation environment, while **ProductionPortConfigurationProvider** produces port configuration to be used in production mode. Both of these provides implement methods requested by the interface **PortConfigurationProvider**.

**Comment by wnorris** [comment]
If everything is sending on port 5001 and listening on port 5002 for the Data Service, how will anyone receive anything? All messages will be send to port 5001 and no one will be listening on that port.

**Comment by zkhalapyan** [comment]
Packets are sent from the sending port number to the receiving port number. When you send a packet using the function `send(byte[] data, int port, String address)` use the receiving end's port number.
