### ISSUE TITLE
Computing New Location from Bearing, Lon, Lat and Time

### ISSUE THREAD

**Issue by ebollens** [zkhalapyan/KimonoNet#15]
Zorayr, how do you propose we compute new locations based on bearing, longitude, latitude and time? I can't seem to find any formulas that handle this simply, but I'm rusty on my spherical polar geometry...

**Comment by ebollens** [comment]
I might try based on some of the discussion here and in the links from here:
http://www.gamedev.net/topic/504860-given-latitudelongitudebearingdistance-where-am-i/

If you haven't already thought this over, I'll proceed as such.

**Comment by ebollens** [comment]
I'll work something up on this by the end of today hopefully. Tomorrow at the latest.

**Comment by zkhalapyan** [comment]
Note sure if you already have the solution, but here is a excerpt from the previous issue discussing location, speed, and bearing: 

The most common dealing with location & speed are the [haversine formula](http://www.movable-type.co.uk/scripts/latlong.html) and the [inverse formula](http://www.ngs.noaa.gov/PUBS_LIB/inverse.pdf) (this paper was written in April, 1975, but is a very famous publication that introduced the inverse formula). The haversine formula uses a spherical model of the Earth resulting in up to 0.3% error while the inverse formula, used in Android's [Location class's source code](http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/2.2_r1.1/android/location/Location.java), is very accurate but a bit more complex treating the Earth as an ellipsoid.
