### ISSUE TITLE
Discard BEACON_ACK packet types?

### ISSUE THREAD

**Issue by zkhalapyan** [zkhalapyan/KimonoNet#17]
From implementation point of view, it seems like BEACON_ACK packets don't really serve any purpose. Would it be better to completely discard this type and just use BEACON?

**Comment by ebollens** [comment]
Yeah, you're right, and in fact that BEACON-ACK functionality is kind of what we always want to use, namely that if you receive a packet that doesn't contain information about youself, then send a beacon back. If it has any information about you, then you do not reply.

**Comment by ebollens** [comment]
I will update the protocol specification later today to remove BEACON-ACK.

Should we keep BEACON as type 2 then, or just change it to type 1?

**Comment by zkhalapyan** [comment]
Great. And I will remove BEACON-ACK from my side.

We should have type 0: Data, and type 1: Beacon. Otherwise, it might be a bit confusing for a reader to jump from type 0 to type 2.
