### ISSUE TITLE
Simulation UI

### ISSUE THREAD

**Issue by ghost** [zkhalapyan/KimonoNet#18]
Hi Zorayr,

I started making the simulation user interface. I'm wondering where I should put my code. In a new package? I would like to know before I push the code for everyone to see.

Thanks.

James

**Comment by zkhalapyan** [comment]
Hi James,

You probably want to create a new package kimononet.simulation and place all your code inside this package. 

-Zorayr 

Отправлено с iPhone

Feb 29, 2012, в 12:44 AM, "james-h" reply@reply.github.com написал(а):

**Comment by zkhalapyan** [comment]
If you have any external libraries, please place the _jar_ version in a top level folder _lib_ i.e. srs, lib.

**Comment by zkhalapyan** [comment]
Hi James, 

Can you please utilize the main method provided in **KimonoNet.java** (located at root source directory) to run your simulation or unit-tests. Just make sure you create methods representing each 'activity' so we can easily comment one line to test our code. For example, have a method _testSimulation()_ that tests your simulation code and then within the main method (i.e. _public static void main(...){}_) call this function to run your code. This way there won't be project entry problems when deploying the code and we can easily switch between running different pieces of the code.

If you are clear on this issue, please review it and close it.

**Comment by ghost** [comment]
Hi Zorayr,

I'm not sure if I should put the unit tests in the main method, because the unit tests are JUnit tests, which are meant to be directly invoked by running the application as a JUnit test, instead of a normal Java Application (which invokes the main method).

James

**Comment by zkhalapyan** [comment]
Don't put the actual unit tests in the main method, but put the initialization method that invokes the unit tests (if any) or the application inside the main method inside _KimonoNet.java_. So in your case, put the code you need to start the simulation in a method called _startSimulation()_ and invoke it from the main method. This way, if instead I want to test out the beacon service, I can just comment out your method invocation and put, _testBeaconService()_, etc.

The goal is to have a single main method and enable easily switching between contexts.

**Comment by ghost** [comment]
So would something like the following work?

<code>

```
private static void startSimulation() {
    EventQueue.invokeLater(new Runnable() {
        public void run() {
            try {
                Simulation window = new Simulation();
                window.frame.setVisible(true);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    });
}

private static void testParcel() {
    (new ParcelTest()).testAddByte();
    (new ParcelTest()).testAddDouble();
    (new ParcelTest()).testAddInt();
    (new ParcelTest()).testAddFloat();
    (new ParcelTest()).testAddLong();
    (new ParcelTest()).testAddString();
    (new ParcelTest()).testAddByteArray();
    (new ParcelTest()).testAddParcelable();
    (new ParcelTest()).testToByteArray();
    (new ParcelTest()).testToParcel();
    (new ParcelTest()).testSetParcel();
    (new ParcelTest()).testGetParcelSize();
    (new ParcelTest()).testCapacity();
    (new ParcelTest()).testCombineParcelables();
}

public static void main(String args[]){
    ...
    testParcel();
    startSimulation();
}
```

</code>

**Comment by zkhalapyan** [comment]
More like this:

``` java
public static void main(){
    //For unit tests, uncomment the code below.
    //startUnitTests();

   //To start the simulation, uncomment the code below.
   //startSimulation();
}

public static void startUnitTests(){
    TestManager testManager = new TestManager();
    testManager.startTesting();
}

public static void startSimulation(){
   Simulation simulation = new Simulation();
   simulation.start();
}
```

This is very hypothetical code that is just for making a point - so your exact code does not have to follow any of it. And of course, this is just 'testbed' code so the finalized version of the project will have a much cleaner look.

**Comment by ghost** [comment]
I pushed new code with the modifications you requested. I am closing this issue for now, but feel free to comment or reopen it if there are other issues. Thanks.
