### ISSUE TITLE
No Need for External Swing/Forms Packages for Simulation UI

### ISSUE THREAD

**Issue by zkhalapyan** [zkhalapyan/KimonoNet#19]
Hi James, 

I just noticed that you are using external libraries for doing GUI designs, and I was wondering why? If possible, could you please only utilize [Javax Swing](http://docs.oracle.com/javase/6/docs/api/javax/swing/package-summary.html) library? This native Java library _"provides a set of 'lightweight' (all-Java language) components that, to the maximum degree possible, work the same on all platforms."_ If we introduce an external library we might jeopardize platform-independence and produce code that is much harder to maintain and distribute. For a small project like this, I am confident that Java's native capabilities will suffice. 

I also suggest you take a look at [Java Layout Managers](http://docs.oracle.com/javase/tutorial/uiswing/layout/visual.html). I took a quick glance at your code and it seems like you are using an external library for doing layout. Try to achieve the same effect using these Layout Managers instead. 

Let me know if you have any questions regarding Javax Swing or Layout Managers and I will try to help you out. The book is also a very helpful resource.

**Comment by ghost** [comment]
I changed the layout to GridBagLayout, which does not require external libs.

**Comment by zkhalapyan** [comment]
Great. Just remove the sources and libs from the repo if you don't need them anymore.

Отправлено с iPhone

Feb 29, 2012, в 5:32 PM, "james-h" reply@reply.github.com написал(а):
