### ISSUE TITLE
Parcel.add(int index, long data) and Parcel.getParcelSize()

### ISSUE THREAD

**Issue by ghost** [zkhalapyan/KimonoNet#20]
Hi Zorayr,

After calling <code>Parcel.add(int index, long data)</code> to add <code>long</code>s to an empty <code>Parcel</code>, <code>Parcel.getParcelSize()</code> seems to always return 0. Is that intentional or not?

James

**Comment by zkhalapyan** [comment]
You should use add(long data).

**Comment by ghost** [comment]
Oh, I was just writing the test case for <code>Parcel.add(int index, long data)</code>, which was why I asked that question.

**Comment by zkhalapyan** [comment]
`Parcel.add(int index, long data)` is used for copying a CRC value into a byte buffer starting from a specific offset. The method doesn't really care about current position in the stack as long as the specified index is within the capacity of the byte buffer. 

Take a look at `putLong(int index, long value)` in [ByteBuffer](http://docs.oracle.com/javase/1.5.0/docs/api/java/nio/ByteBuffer.html).

**Comment by ghost** [comment]
Ah, I see. So I guess I don't have to check <code>Parcel.getParcelSize()</code> in this case. Alright then, I will close this issue.
