### ISSUE TITLE
Timestamps Testing

### ISSUE THREAD

**Issue by ghost** [zkhalapyan/KimonoNet#22]
Since timestamps vary with system time, I need to be able to fix timestamps during testing. Would it be fine that I create a new class that returns the actual time during normal operation, but returns a fixed time during testing, and then modify your code to use this class instead of <code>System.currentTimeMillis()</code>?

So for example, I create a <code>KimonoTime</code> class under <code>kimononet.util</code>. Then I replace all instances of <code>System.currentTimeMillis()</code> with <code>KimonoTime.currentTimeMillis()</code>. When I want to do testing, I do <code>KimonoTime.setTesting(true)</code> before doing anything else.

**Comment by zkhalapyan** [comment]
Why do you need to fix time?

**Comment by ghost** [comment]
It will make testing easier.

For example, if a packet contains a timestamp, the timestamp would change during every test run. If I force the time to be constant, then the packet contents can be guaranteed to be identical every run.

Another example is testing GeoVelocity. I can increment time at my discretion so I can have full control over testing speed calculations.

**Comment by zkhalapyan** [comment]
Ok I will commit a time provider implementation.
