### ISSUE TITLE
Gathering and Analyzing Data

### ISSUE THREAD

**Issue by zkhalapyan** [zkhalapyan/KimonoNet#24]
Previously, @james-h concluded that the following are important factors for analyzing the results:
1. **Packets Lost**: Number of packets lost.
2. **Packet Delivery Percentage**: (Number of data packets successfully received by destination nodes) / (Total number of data packets sent by source nodes)
3. **Routing Packet Overhead**: (Number of control packets) / (Number of successfully received data packets)
4. **Average Latency**: The mean time (in seconds) taken by the data packets to reach their respective destinations.
## 

What would be the best way to gather the data required for these calculations without adding too much overhead to the current implementation?

**Comment by zkhalapyan** [comment]
@ebollens,

Should we also add **GREEDY vs. PARAMETER ROUTING** ratio?

**Comment by ebollens** [comment]
Definitely Zorayr!

**Comment by zkhalapyan** [comment]
I think the best approach would be to account for the following fields:
1. **Packets Lost**: Calculated as difference between the number of packets that left the source, and the number of packets that arrived at the destination.
2. **Packet Delivery Percentage**: Calculated as the ratio between the number of packets received at the sink and the number of packets sent at the source.
3. **Routing Packet Overhead**: Calculated as the ratio of the number of _sent/received_ beacon packets over the number of _sent/received_ data packets. 
4. **Greedy Ratio**: Calculated as the ratio of the number of sent packets that used greedy over the number of sent packets that used parameter routing.

I left out any time related ratios as we are only testing on a single node and it's hard to rig time. I can still include this but the values are not going to reflect anything relevant.

**Comment by zkhalapyan** [comment]
@wnorris,

Please remember to notify the stat monitor when you send or receive any packets. 

``` java
StatPacket p = new StatPacket(dataPacket, currentPeer, forwardMode);
agent.getStatMonitor().packetSent(p);
//or
agent.getStatMonitor().packetReceived(p);
```

Let me know if this doesn't work out for you.

**Comment by zkhalapyan** [comment]
What should we do with dropped packets at the source? @wnorris, can you just call `sentPacket()` at the `StatMonitor`, even though you dropped the packet?

**Comment by ghost** [comment]
Should `sentPacketCount == beaconPacketCount + dataPacketCount`? Currently, that's not the case, which explains the negative numbers in the stats.

**Comment by zkhalapyan** [comment]
The statistical monitor component of the application is ready - more updates, improvements, and optimization will be covered in other issues.

**Comment by ebollens** [comment]
That would make sense @james-h
