### ISSUE TITLE
How to Extract an 8 byte string from Parcel

### ISSUE THREAD

**Issue by wnorris** [zkhalapyan/KimonoNet#27]
I need to get HDR-DST-ID which I am under the impression is the String identifier. I can't really figure out how I can pull out a specified length string from a parcel.

**Comment by zkhalapyan** [comment]
I believe that **HDR-DST-ID** is a MAC-48 address. @ebollens  can you please confirm this? 

If it is indeed a MAC address, then just use the parsing method in the _PeerAddress_ class. I highly doubt you will need to parse strings for this project.

**Comment by wnorris** [comment]
I thought that HDR-DST-LOC (24 bytes) was the PeerAddress or MAC.

**Comment by ebollens** [comment]
Zorayr is correct that HDR-DST-ID is a MAC address.

HDR-DST-LOC meanwhile is the location of the destination in the location format.

**Comment by zkhalapyan** [comment]
HDR-DST-LOC stands for HEADER-DESTINATION-LOCATION and is the geo location of the destination peer, mapped to a GeoLocation object. Each Peer is identified by a GeoLocation, PeerAddress, GeoVelocity.

**Comment by ebollens** [comment]
Zorayr is correct.

**Comment by wnorris** [comment]
Got it.
