### ISSUE TITLE
Random Time Offset for Sending Beacon Packets

### ISSUE THREAD

**Issue by zkhalapyan** [zkhalapyan/KimonoNet#28]
Please specify the algorithm for a random time offset before sending becaon packets. These will prevent attempts at the MAC layer to send packets at the same time.

**Comment by ebollens** [comment]
This is only a problem for "test" mode, which the protocol itself doesn't account for.

Consequently, I'll leave this to implementation. In reality, offset will exist because nodes will not come online at the same time, so there won't be a MAC conflict.

**Comment by zkhalapyan** [comment]
Random offset is controlled by an environment variable `beacon-service-timeout-random-additive`. It is currently set to 20%.

With the new addition, actual timeout is calculated as follows:
 `timeout = beacon-timeout + rand() * beacon-timeout * beacon-service-timeout-random-additive`
