### ISSUE TITLE
Typo in protocol.docx

### ISSUE THREAD

**Issue by ghost** [zkhalapyan/KimonoNet#30]
Hi Eric,

I believe there is a typo in <i>protocol.docx</i> under the section <i>4.1.2. Common Header Format</i>:

<i>The common header has a total length of 48 bytes.</i>

should be

<i>The common header has a total length of <b>44</b> bytes.</i>

James

**Comment by ebollens** [comment]
Good catch James. Next version will be updated to fix this.

**Comment by wnorris** [comment]
@james-h I believe this should be closed now, no?
