### ISSUE TITLE
Peer(PeerAddress address, String name)

### ISSUE THREAD

**Issue by ghost** [zkhalapyan/KimonoNet#32]
The constructor `Peer(PeerAddress address, String name)` creates a new `GeoVelocity` object since an existing one is not specified. For consistency, should it also do the same for `GeoLocation`? So the constructor would become:

``` java
public Peer(PeerAddress address, String name) {
    this.name = name;
    this.address = address;
    this.location = new GeoLocation();  // The new line of code.
    this.velocity = new GeoVelocity();
}
```

Since there is no `GeoLocation` constructor that takes zero arguments, maybe you could create one just like how you did it in `GeoVelocity`?

**Comment by ghost** [comment]
Yeah I think you should do this to avoid current location being `null`, which will cause the program to crash when you try to do `toParcel`.

**Comment by zkhalapyan** [comment]
If the location has not been specified, there should be no reason to convert a peer to a parcel representation. And if we specify a default location, then we are going to have a peer sending beacons from the North pole i.e. (0, 0). 

I modified `toParcel()` to throw a new `ParcelException` if any of the values required for parceling a peer has not bee specified.
