### ISSUE TITLE
Packet.parse(Parcel parcel)

### ISSUE THREAD

**Issue by ghost** [zkhalapyan/KimonoNet#35]
In `Packet.parse(Parcel parcel)`, I think

``` java
...
if(parcel.getParcelSize() > 0){
...
```

is not right, because `parcel.getParcelSize()` will always be equal to `HEADER_LENGTH` at this point.

I think it should be:

``` java
...
if(parcel.capacity() > HEADER_LENGTH)
...
```

Also, there is something wrong with `parcel.slice()`. Although the newly-created parcel has its capacity set to the length of the contents, which is correct, converting this parcel to a byte-array will result in an array with the length of the original packet. Try this:

``` java
contents = parcel.slice();
System.out.println(contents);
System.out.println(contents.toByteArray().length);
```

**Comment by zkhalapyan** [comment]
The following is the documentation for the slice method for `ByteBuffers`.

> Creates a new byte buffer whose content is a shared subsequence of this buffer's content.
> The content of the new buffer will start at this buffer's current position. Changes to this buffer's content will be visible in the new buffer, and vice versa; the two buffers' position, limit, and mark values will be independent.
> 
> The new buffer's position will be zero, its capacity and its limit will be the number of bytes remaining in this buffer, and its mark will be undefined. The new buffer will be direct if, and only if, this buffer is direct, and it will be read-only if, and only if, this buffer is read-only.

**Comment by ghost** [comment]
I think your code is still bugged. Shouldn't it be:

``` java
    public void parse(Parcel parcel){

        //The packet must have at least enough bytes to contain 
        //the header section.
        if(parcel.getParcelSize() < HEADER_LENGTH){
            throw new PacketException("Malformed or missing packet header.");
        }

        //This should only be done at the top of the parsing hierarchy. 
        parcel.rewind();

        parcel.getByteArray(magic);
        version = parcel.getByte();
        type = PacketType.parse(parcel.getByte());
        peer = new Peer(parcel);

        if(parcel.capacity() > HEADER_LENGTH){
            contents = parcel.slice();
        }

    }
```

Also, regarding `slice`, what I meant was that even after a `ByteBuffer` is sliced, the entire backing array of the buffer will still be returned by the `array` method. I guess that's how `ByteBuffer` is designed, but should we consider working around this issue, or is this even an issue?

**Comment by ghost** [comment]
I am still getting errors in my tests. At the end, I believe

``` java
        if(parcel.capacity() > 0){
            contents = parcel.slice();
        }
```

should be

``` java
        if(parcel.capacity() > HEADER_LENGTH){
            contents = parcel.slice();
        }
```

**Comment by zkhalapyan** [comment]
Fixed by the last commit.
