### ISSUE TITLE
Data Header Size

### ISSUE THREAD

**Issue by wnorris** [zkhalapyan/KimonoNet#38]
The protocol specifies:

"The total length of the Type 0 header format, including the common header, is 92 bytes."

I believe it should be 96 bytes.

The common header is 48 bytes according to the protocol and the Type 0 header consists of:
HDR-DST-ID (8)
HDR-DST-LOC (24)
HDR-FWD-DST-ID (8)
HDR-FWD-MODE (1)
HDR-DATA-LEN (2) 
HDR-QOS (1)
HDR-HDR-CHK (4)
Total: 48

48+48 = 96 not 92

**Comment by wnorris** [comment]
So actually I am adding up the common header now:

HDR-MAGIC (2)
HDR-VERSION (1)
HDR-TYPE (1)
HDR-SRC-ID (8)
HDR-SRC-LOC (24)
HDR-SRC-VEC (8)

and getting 44 instead of 48 like it says. This then corrects the other error of not adding up to 92.

I think "The common header has a total length of 48 bytes." should instead be changed to 44.

**Comment by ebollens** [comment]
This was just corrected in my latest commit

**Comment by wnorris** [comment]
Sounds good.
