### ISSUE TITLE
How to access routing table

### ISSUE THREAD

**Issue by wnorris** [zkhalapyan/KimonoNet#39]
How do I access the routing tables for forwarding packets in the data service. @zkhalapyan, this should be updated and maintained by the beacon service correct?

I think I am blocked from implementing any routing on this presently, unless it has been implemented somewhere I can't find.

**Comment by zkhalapyan** [comment]
`PeerAgent` has two routing tables populated by the beacon services. Here is the documentation that I pulled out of the code:

``` java
 /**
  * Neighboring peer's mapped to a peer address. This is ROUTING_TABLE_1 
  * described in the protocol documentation. To access the peers table, use
  * method {@link #getPeers()}.
  * 
  * @see #getPeers()
  */
private HashMap<PeerAddress, Peer> peers;

 /**
  * Stores second-hop neighbors: given a peer address, it will get the peers
  * map of that peer if it exists. This is ROUTING_TABLE_2 specified in the 
  * protocol documentation. 
  * 
  * @see #getPeers2()
  */
private HashMap<PeerAddress, HashMap<PeerAddress, Peer>> peers2;
```

**Comment by wnorris** [comment]
Great, thanks!
