### ISSUE TITLE
All Services Must Implement Service Interface 

### ISSUE THREAD

**Issue by zkhalapyan** [zkhalapyan/KimonoNet#42]
Any thread or object that can be started or shutdown must implement `kimononet.service.Service` interface  which mandates objects to include two methods: `startService()` and `shutdownService()`. 

Utilizing this approach will allow a consistent way to start or stop services such as beacon service, data service, and also monitoring services.

**Comment by wnorris** [comment]
Data Service has been updated since this issue was opened to match this interface.

**Comment by zkhalapyan** [comment]
The following classes have implemented Service interface:
- **GeoService**: Responsible for updating current peer's velocity and location. 
- **BeaconService**: Sends and receives beacon packets and also updates routing tables.
- **DataService**: Utilizes routing tables and routing algorithms to send and receive data packets.
