### ISSUE TITLE
Environment Variables i.e. Nobs 

### ISSUE THREAD

**Issue by zkhalapyan** [zkhalapyan/KimonoNet#43]
Environment variables are configuration variables that allow to modify the settings of the current nodes environment. The following environment variables are currently at place:
1. **beacon-service-timeout** This value indicates how long in seconds a beacon service waits for receiving a beacon from a neighbor before sending out its own beacon.
2. **max-beacon-peers** Maximum number of peers to be included in beacon packets.
3. **node-failure-rate** With some frequency specified by this value, nodes will completely shutdown. This allows simulation of hostile environment.
4. **packet-loss-rate** Packets will be discarded on the receiving end at some frequency according to this value. For example 0.1 will indicate 10% loss at each node.
5. **max-transmission-range** Packets above received further away than this distance specified in meters will be discarded.
6. **average-gps-accuracy** Indicates the average value of some distribution curve to be determined.
## 

Are there any other values to be considered?

**Comment by ebollens** [comment]
I assume that beacon-service-timeout is similar to `TMR-BEACON-VALUE`?

Besides that, looks good for testing and tuning.
