### ISSUE TITLE
Simulation Functionality Overview and Changes

### ISSUE THREAD

**Issue by zkhalapyan** [zkhalapyan/KimonoNet#45]
The following still needs to be done for the simulation component: 

**UI Changes**
- [DONE] Create full screen frame display. 
- [DONE] Functionality for changing map dimensions.
- [DONE] Disable editing property names. 
- [DONE] Add grid display for a map. 
- [DONE] Add some indication of a simulation running state i.e. green icon for running/red icon for stopped.
- [DONE] Side note: to start the simulation for node, click on the `startServices()` for each node.
- [DONE] Change UAV image. Also the image should be much smaller. 
- [DONE] Once Zorayr has the StatData completed, use the data to update the statistics info. Again, make this into a method that takes in a StatData object and displays the result. 
- [DONE] Add delete peer button.
- [DONE] Add labels on top of content boxes i.e. "Peers", "Peer Property", "Environment Properties".
- [DONE] Create environment variables display. Cane make it similar to the table. 

**Node Simulation**
- [DONE] Translate node's current location to (x,y) position on the map.
- [DONE] Direct the node's image to the specified bearing value. 
- [DONE] Use a polling architecture to draw each node on the map at a certain interval.
- [DONE: All UI updates are done by the `Simulation.refresh()` method. This method also forces a repaint of the `SimulationPanel`. All the painting is done by `SimulationPanel.paintComponent()`] Make sure to encapsulate node drawing/handling functionality inside a single method.

**OO Changes**
- [DONE] Encapsulate functionality within PeerPropertiesTable, PeerList, EnvironmentPropertiesTable, and also StatDisplay class.

**ToDo: Zorayr**
- Add random address factory method to the PeerAddress class
- Add address validation static method to the PeerAddress class
- Implement random waypoint within the GeoDevice 
- Implement statistics analysis within StatData class. 
- Create StatResults class

**Comment by ghost** [comment]
I believe the simulation UI is pretty much done now. If there is anything else that should be added, please let me know.
