### ISSUE TITLE
Services and Threads

### ISSUE THREAD

**Issue by ghost** [zkhalapyan/KimonoNet#47]
Hi Zorayr,

Once a thread has been started, it cannot be started again, even if you stop it first. You must create a new thread if you want to start it again, or else you get `IllegalThreadStateException` (http://stackoverflow.com/questions/1215548/is-it-legal-to-call-the-start-method-twice-on-the-same-thread).

Therefore, I modified the `PeerAgent.startServices()` method as follows:

``` java
    public void startServices(){
        //Create the services used by the agent.
        this.beaconService = new BeaconService(this);       
        this.geoService    = new GeoService(this);

        this.geoService.startService();
        this.beaconService.start();

    }
```

Instead of instantiating new `BeaconService` and `GeoService` objects in the constructor of `PeerAgent`, I do it every time the services are started.

Even though I fixed the issue, I'm still leaving it open so you will be aware of it.

**Comment by zkhalapyan** [comment]
Yes, that's correct. Threads are not supposed to be started again.

Отправлено с iPhone

Mar 15, 2012, в 2:48 AM, "james-h" reply@reply.github.com написал(а):

**Comment by ghost** [comment]
I guess I will close this issue then since you are aware of it. I fixed this bug for you in your `PeerAgent` code so the simulations can be start/stop repeatedly by the user. BTW, the start/stop function is actually working now in the UI.

**Comment by zkhalapyan** [comment]
Nice! 

Отправлено с iPhone

Mar 15, 2012, в 3:21 AM, "james-h" reply@reply.github.com написал(а):
