### ISSUE TITLE
Received Packets Not Counted

### ISSUE THREAD

**Issue by zkhalapyan** [zkhalapyan/KimonoNet#55]
Delivered packet count is always zero.

**Comment by ghost** [comment]
Maybe this is caused by `StatPacket.isSink()` never returning `true`?

**Comment by zkhalapyan** [comment]
I have successfully tested StatPacket.isSink() - that shouldn't cause any problem.

**Comment by ghost** [comment]
Then could it be that packets really aren't reaching their final destinations?

**Comment by wnorris** [comment]
Zoro had said earlier that he saw it printing out that some of them had made it to the destination but that it still counted it as zero. I think the problem is elsewhere.

**Comment by zkhalapyan** [comment]
This problem was fixed by (65c089f1e03d3102fe42597844e2b3dd4d6418a5) - The issue was that the results were getting calculated before the packets were getting sent.
