### ISSUE TITLE
Checking for Exceptions

### ISSUE THREAD

**Issue by ghost** [zkhalapyan/KimonoNet#56]
Hey guys,

If you run using Git Bash instead of Command Prompt, you get to have `grep`, which you can use to search for the word `Exception` in the output.

You can also use `tee` to write the output to file at the same time so you can check the other output.

Example: `java KimonoNet mode-cl 10 1000 1000 1 100 10 | tee foo.txt | grep Exception`

**Comment by zkhalapyan** [comment]
A much better way is actually to run eclipse in debug mode. This will exactly show you which thread has stopped at which exception.

**Comment by zkhalapyan** [comment]
The issue describes a technique and is not critical to development.
