### ISSUE TITLE
Turning Off 2-Hop Routing in Order to Compare to GPSR

### ISSUE THREAD

**Issue by zkhalapyan** [zkhalapyan/KimonoNet#60]
In order to have some valid comparison data, it is necessary to be able to turn off 2-hop routing and just run GPSR simulation. With this addition, our final report can include data gathered from GPSR simulation and data gathered from KN simulation both running on top of the same framework.

For public interface, the data service should include a method such as `turnOn2HopRouting()` or `set2HopRouting(bool)` in order to change the current mode of routing.

**Comment by wnorris** [comment]
This is not something that will be done in the DataService. The DataService sends the packet to the routing protocol which only uses peers1 not peers2. Peers1 should be automatically updated by an asynchronous service that can detect when peers from peers2 have come into range.

This service should simply be turned off when we want to turn off 2hop routing, but I did not write this. I was under this impression you did Zoro, did you not? If not this is a very critical part that still needs to be implemented.

If you did write it let me know where it is and I can add this functionality.

**Comment by zkhalapyan** [comment]
Beacon Service - which is the only service on my side that updates peers1 and peers2 - does the following: (abridged version)
1. Parses the beacon packet that was received and checks for validity (i.e. CRC check, and loopback check).
2. The source peer of the packet is added/updated inside the peers1 table.
3. Neighbor peers included in the beacon packet are mapped to peers2 table. So peers2 represents: <beacon-source-peer-address, neighbors-included-in-the-beacon-packet>.

There are no calculations or routing related algorithms on the beacon service.

**Comment by wnorris** [comment]
Yea, we need another service that is asynchronously updating peer locations and then moving them from peers2 table to peers1 table if they are now in range...

**Comment by zkhalapyan** [comment]
Let's not write another service. The calculations should be done within one method which would be called every time a new data packet is received.

**Comment by wnorris** [comment]
Where is the global dial for how far the range of a peer is?

**Comment by zkhalapyan** [comment]
It's the `max-transmission-range` property of the peer's environment variables. This is how I do it within `BeaconService`

``` java

//If the value is not set within the environment, then maxRnage will be
//set to null.
//ToDo: Remove association between beacon service and environment variables.
maxRange = Integer.parseInt(agent.getEnvironment().get("max-transmission-range"));

//If the peer is out of range, than ignore the packet.
if(maxRange != null 
   && agent.getPeer().getLocation().distanceTo(packet.getPeer().getLocation()) > maxRange) {
    continue;
}

```

Remember that distance is always in meters.

**Comment by wnorris** [comment]
Also can you explain peer table2? I'm assuming that in peer table 1 it is the address of the neighbor and the Peer object of the neighbor and in peer table2 it is the address of the neighbor that told us about the two hop peer that maps to another table with the address of the twohop peer and the Peer object of the twohop peer. Is that correct?

Alternatively I could see it being implemented such that: peer table 1 is the current node address mapped to the Peer object for the neighbor. Peer table 2 would then be the current node address mapped to the address of the neighbor that knows about the two hop peer which is mapped to the Peer object for the twohop peer.

**Comment by zkhalapyan** [comment]
The received beacon packet in its most simple structure has the following fields:

```
ReceivedBeaconPacket
  -SourcePeer //a single peer who sent the beacon to us.
  -Neighbors[]  //peers who are in the reach of the peer that sent us this beacon packet.
```

Now when the `BeaconService` receives this, it stores the  `SourcePeer` within `peers` table and adds all the neighbors to the `peers2` table mapped to the source peer, creating a structure `<SourcePeer, Neighbors[]>`. So if you used the peer about it's direct neighbors it would return you the `peers` table. On the other hand, if you asked the peer for the neighbors of it's direct neighbors, it would return you `peers1`.

**Comment by zkhalapyan** [comment]
You will find `move(..)` method helpful in calculating new locations from velocity and dT.
