### ISSUE TITLE
Uncomented GeoLocation Exception, and Using Hostility Factor

### ISSUE THREAD

**Issue by ghost** [zkhalapyan/KimonoNet#61]
Hey Zorayr,
- Any reason why the exception throwing in `GeoLocation.setLocation()` is commented out? Looking at the Blame view, I think it might be Wade that did this. Is it OK that I uncomment it?
- Do you want to me add hostility factor option in the UI? Should it be a new popup dialog, or is it a Peer Environment variable?

**Comment by zkhalapyan** [comment]
- I don't see why not. If it is helpful on your side to catch the exception for validation purposes, go ahead and uncomment it.
- Hostility factor is an extrinsic property as in it does not depend on the peer itself. As such it should be stored in a local property within the UI simulation. If you look at the implementation of KiNCoL, it would make a better sense .
- Also, can you please put separate issues on separate issue threads. This way it will be much easier to look up previous issues and keep the repository manageable.

**Comment by wnorris** [comment]
Yea sorry, didn't mean to push this change, I only had it commented out because that Exception hadn't been implemented (or maybe just not pushed) yet and I needed to comment it out at the time to compile.

Feel free to uncomment.
