### ISSUE TITLE
node-failure-rate?

### ISSUE THREAD

**Issue by ghost** [zkhalapyan/KimonoNet#62]
I noticed in the `DefaultPeerEnvironment` there is a parameter called `node-failure-rate`. It seems to me that this is the hostility factor. However, this seems to be not used at the moment; rather, your KiNCoL stores the hostility factor in a separate `hostilityFactor` variable. Was this a mistake?

**Comment by zkhalapyan** [comment]
Yes, I was supposed to take this out after I introduced hostility factor within `KiNCoL`. It just seemed very unnatural for a peer to store a probability of it blowing up etc. Disregard `node-failure-rate` property for now.

**Comment by ghost** [comment]
Cool I guess I could add a option in the UI (kinda like the edit map dimensions) for the node failure rate.
