### ISSUE TITLE
Destination Sink Should Be Fixed

### ISSUE THREAD

**Issue by ebollens** [zkhalapyan/KimonoNet#65]
@zkhalapyan @james-h The destination node (sink) should be fixed in both GUI and KiNCoL

**Comment by ghost** [comment]
I know this isn't too important, but I'm thinking of representing the destination node with a different graphic. But before I do that, I need to make sure: since the destination node is not moving, is it a base station instead of a UAV?

**Comment by zkhalapyan** [comment]
@james-h, you can decide on this. It can either be a base station or a UAV.

**Comment by ghost** [comment]
In a hostile environment, if the destination sink explodes, should the simulation stop?

**Comment by zkhalapyan** [comment]
My enemies are very considerate of my sinks/source agents - they never explode.

**Comment by ebollens** [comment]
I think this is resolved, at least from KiNCoL 

@james-h please reopen if I'm wrong because GUI hasn't implemented yet - I'm unsure as all my simulations are happening within KiNCoL for now
