### ISSUE TITLE
Multiple Sources to Send to Sinks

### ISSUE THREAD

**Issue by ebollens** [zkhalapyan/KimonoNet#67]
Multiple sources should be sending packets to the sink so that we don't get one source that's an outlier that can't communicate well with the rest of the network graph.

**Comment by zkhalapyan** [comment]
KiNCoL has implemented this. @james-h, can you update us on the UI side?

**Comment by ebollens** [comment]
@zkhalapyan this is good from the KiNCoL side - @james-h what's status on GUI?

**Comment by ghost** [comment]
GUI has been updated!
