### ISSUE TITLE
Debug Output "Off" Switch in KiNCoL

### ISSUE THREAD

**Issue by ebollens** [zkhalapyan/KimonoNet#69]
We should be able to squelch debug output (by default) in KiNCoL so that you don't get all those "scary sounding" errors that aren't actually bad about dropped packets.

**Comment by zkhalapyan** [comment]
Commit (e1900e2b2067d7844c88224d0020342f8df3126a) introduced a `Logger` class that has three different types of output: `INFO`, `DEBUG`, and `ERROR`. These different types of outputs can statically be turned on or off. To log to either of the streams use methods: `Logger.info(message)`, `Logger.error(message)`, or `Logger.debug(message)`. By default, only information stream is enabled.
