### ISSUE TITLE
CRC Placement within Packets

### ISSUE THREAD

**Issue by zkhalapyan** [zkhalapyan/KimonoNet#7]
Implementation-wise, it is much more convenient to place checksums at the end of the packet. Accordingly, beacon packet's field members should be ordered as such:
1. Neighboring Peer Count
2. Neighboring Peer Reports
3. CRC32

**Comment by ebollens** [comment]
That goes against the paradigm established by basically every protocol in existence.

Placement in the middle of the packet would just require the following...

To create:
1. Generate packet contents except CRC-32.
2. Set CRC-32 field to 0x00000000.
3. Compute CRC-32.
4. Place CRC-32 in CRC-32 field.

To compare:
1. Copy CRC-32 to local variable.
2. Set CRC-32 field to empty.
3. Compute CRC-32 of packet.
4. Compare with local variable.

**Comment by zkhalapyan** [comment]
Implementation wise, it's much easier to append the CRC at the end. Most of the protocol implementations of the world use C/C++ that supports pointers unlike Java.

If there are restrictions for this from the protocol side, I can make it work but I prefer not to.

**Comment by zkhalapyan** [comment]
I am using a _ByteBuffer_ to either push or pop data - so to place a CRC in the middle, I will need to copy an array of bytes twice: once for initialization to 0x0 and another time for the actual value.

**Comment by ebollens** [comment]
Very well. CRC can go at end -.-

**Comment by ebollens** [comment]
I will update the specification to include this change.
