### ISSUE TITLE
ROUTING-TABLE-2 Maintenance

### ISSUE THREAD

**Issue by ebollens** [zkhalapyan/KimonoNet#71]
@wnorris it appears that ROUTING-TABLE-2 is getting entries added to it even when nodes are already in it. I have not confirmed it within the code itself, but look at these results for `mode-cl 20 500 500 0 10 200 5000`, which is for 20 nodes:

```
Agent:   peer-0 # of peers:      5 # of peers2:      21
Agent:   peer-1 # of peers:      8 # of peers2:      52
Agent:   peer-2 # of peers:      9 # of peers2:      76
Agent:   peer-3 # of peers:      13 # of peers2:     126
Agent:   peer-4 # of peers:      15 # of peers2:     136
Agent:   peer-5 # of peers:      11 # of peers2:     113
Agent:   peer-6 # of peers:      7 # of peers2:      59
Agent:   peer-7 # of peers:      10 # of peers2:     93
Agent:   peer-8 # of peers:      15 # of peers2:     122
Agent:   peer-9 # of peers:      11 # of peers2:     94
Agent:   peer-10 # of peers:     6 # of peers2:      39
Agent:   peer-11 # of peers:     11 # of peers2:     115
Agent:   peer-12 # of peers:     10 # of peers2:     91
Agent:   peer-13 # of peers:     12 # of peers2:     110
Agent:   peer-14 # of peers:     4 # of peers2:      35
Agent:   peer-15 # of peers:     12 # of peers2:     111
Agent:   peer-16 # of peers:     14 # of peers2:     128
Agent:   peer-17 # of peers:     12 # of peers2:     123
Agent:   peer-18 # of peers:     13 # of peers2:     118
Agent:   peer-19 # of peers:     3 # of peers2:      16
```

This has two consequences:
- A node might build ROUTING-TABLE-1 using stale data from ROUTING-TABLE-2 because of an old node's location before it switched direction.
- A node has to do a lot of extra computation to handle the fact it has so many nodes in ROUTING-TABLE 2.

**Comment by zkhalapyan** [comment]
The size of peers2 table is actually the total number of 2-hop neighbors. With 20 nodes, at max peers2.size() == 19, but if we iterate through each neighbor of peers2 entires, the accumulated value will be higher:

``` java

int peers2NeighborCount = 0;

for(PeerAddress address : agent.getPeers2().keySet()){
    peers2NeighborCount += agent.getPeers2().get(address).size();
}
```

**Comment by wnorris** [comment]
I did not write code that adds to peer table2 :-/

Let me know if you still want me to look into this.
On Mar 21, 2012 6:16 PM, "Eric Bollens" <
reply@reply.github.com>
wrote:
