### ISSUE TITLE
Control Overhead

### ISSUE THREAD

**Issue by ebollens** [zkhalapyan/KimonoNet#74]
Change control overhead to be calculated as:

```
TOTAL_CONTROL_PACKETS / [TOTAL_CONTROL_PACKETS + TOTAL_SEND_DATA_PACKET_COUNT]
```

This is because we're reporting it this way in the final report. I'm also not sure how we're getting the current method.

**Comment by zkhalapyan** [comment]
The current control overhead is calculated as `sent_beacon_packets` / `total_sent_packets`.
