### ISSUE TITLE
Images Not Loading in GUI

### ISSUE THREAD

**Issue by ebollens** [zkhalapyan/KimonoNet#75]
Images aren't loading under straight run in Netbeans.

Probably an issue for JAR too.

**Comment by ghost** [comment]
The UI attempts to load the PNG files from the current working directory. Try copying the PNG files to the BIN folder.

**Comment by ghost** [comment]
Never mind, I found a better way to load the images. I will commit the code shortly. Please try it out with Netbeans and JAR and let me know if there are any issues.

**Comment by ghost** [comment]
I tried exporting to runnable JAR, and it seems to work fine. I will close this issue, but feel free to reopen it if you run into any issues.

**Comment by ebollens** [comment]
Please include a JAR file with this working in the repository.

**Comment by ghost** [comment]
I added the JAR file to the repo.

How to run JAR file?
- Simply double-click it, or
- From command line: `java -jar KimonoNet.jar [command line arguments]`

**Comment by zkhalapyan** [comment]
I am running into an issue running the JAR:  "Could not find main class KimonoNet." Did you configure your manifest correctly?

**Comment by ghost** [comment]
Works on my machine. Tried double-clicking, and also via command line -- either way, it works fine for me.

**Comment by zkhalapyan** [comment]
Did you export a executable JAR? I exported a new JAR with the lastest version of the code. Let me know if there are any issues running it.

**Comment by ghost** [comment]
Runs just fine!
