### ISSUE TITLE
Image Loading Issues

### ISSUE THREAD

**Issue by zkhalapyan** [zkhalapyan/KimonoNet#76]
When running the simulator via the command line as such "mode-gui", images failed to load. Can you research the issue and see if it is there are better approaches to load the images.

**Comment by ghost** [comment]
The UI attempts to load the PNG files from the current working directory. Try copying the PNG files to the BIN folder.

**Comment by ghost** [comment]
Never mind, I found a better way to load the images. I will commit the code shortly. Please try it out with Netbeans and JAR and let me know if there are any issues.

**Comment by ghost** [comment]
I tried exporting to runnable JAR, and it seems to work fine. I will close this issue, but feel free to reopen it if you run into any issues.
