### ISSUE TITLE
Packet Handling Design Concepts

### ISSUE THREAD

**Issue by zkhalapyan** [zkhalapyan/KimonoNet#9]
There are three different types of packets that KimonoNet either sends or receives: beacon packets, beacon ack packets, as well as data packets. To handle these packets, there are three opposing design concepts:

**Multi-Service Approach**
Each type of packet will be associated with a specific service, which in most generic terms, is considered to be an individual, running thread.  As such, any peer will have a beacon sending service, beacon receiving service (this service will be primarily listening to incoming beacons or beacon ACKs and respond accordingly), and also data sending service, and a data receiving service. Although this design is very modularized and object oriented, it suffers from efficiency issues as broadcast packets will be handled in several services and discarded in all except one.

**Multi-Service, Non-Broadcast Approach**
Yet another approach is to modify the multi-service approach in a way that each service will listen to a specific port; hence, proving broadcast packets unnecessary. This seems a like a nice design, but running multiple peers bound on the same port numbers on a single simulation machine is impossible i.e. two sockets cannot be pound to port 80. 

**Dual-Service Approach**
With this design approach, there will be two services running: one service for receiving packets and one service for sending packets. Upon receiving a packet, the receiving service will add it to a Beacon Queue, Beacon Ack Queue, or Data Queue depending on the packet type and will assume that the packet will be handled accordingly within a beacon service, beacon ack service, or the data service. If at any time a service would like to send a packet, it enqueues the packet into a sending service's priority packet queue whereby the packet will be send as soon as it is popped. The advantage of using this design is that all broadcast packets will be handled once and will only be two network-related services running at any time. However, the design adds an additional layer of services above the network services that have to be maintained.

Would appreciate some feedback on this issue.

**Comment by ebollens** [comment]
I think we've fleshed this out in discussion.

Want to summarize the conclusion here and close the issue?

**Comment by zkhalapyan** [comment]
The final solution implemented in the project is a hybrid of the initially mentioned design concepts. The new design has two main services running at any time: a **beacon service** and a **data service**. Beacon service is a simple single thread that uses a blocking socket-read method to wait for a certain period before sending in a beacon packet. Information exchanged via this service will be stored in two hash maps in the peer agent class representing ROUTING-TABLE-1 & ROUTING-TABLE-2 as described in the protocol specification. 

Data service will have two running threads: a data receiving thread and a data sending thread. These two threads will communicate via a [PriorityBlockingQueue](http://docs.oracle.com/javase/1.5.0/docs/api/java/util/concurrent/PriorityBlockingQueue.html) and will use [wait/notify](http://www.java-samples.com/showtutorial.php?tutorialid=306) thread control pattern for efficiency. @wnorris  is currently implementing this service.
